### PR TITLE
Python principles

### PR DESCRIPTION
**Pull request by medic-code**
Here's the Python Principles sections that I have a base for now. I've separated them out into different files for better reviewing. 

Things still to do 
1. The application walk through section to do (Alex has kindly offered to do this - I've provided some high level overview guidance on a suitable walk through). 

@chris-lovejoy - I notice we have the medical calculator walk through so we might actually be repeating ourselves by doing this section, what do you think ?

2. I'd like to add some coding problems to get them into problem solving - So ill make a few more commits with this.

3. Review of the content for accuracy and interactivity. Also please note things that could be removed if you don't think its essential. I realise how much is covered in this multi part exercise.

### CODE REVIEW

**Comment by chris-lovejoy** [comment]
Hey Aaron, I've had a quick look through these and looks great! Shall I merge the PR into main, or wait until you've added the points you wanted to above?

Maybe a _little_ bit of repetition with the medical calculator exercise, not _major_ but in my opinion this is actually fine.

In terms of the Review of content, happy to get somebody else to do that to help lighten the load.

**Comment by AlexTeslenko** [comment]
@medic-code I've been reviewing the PR, looks really very informative and well-structured so far. 
In my opinion, there is already a lot of information to process so maybe an additional walk-through application would be too much for students for one week.

**Comment by chris-lovejoy** [comment]
Yeah this is a great point Alex. I think we can either push the coding calculator notebook into a different week, or make it optional -> and for the python principles exercises I think we can split across both the lecture and practical session for that week (to give more time)

**Comment by medic-code** [comment]
Hi @AlexTeslenko @chris-lovejoy Sorry for the late reply, last couple of days been incredibly busy since creating the PR. 

Thanks Alex on your initial feedback! I'll be spending today adding a few problems for each exercise for the students to get to grips with.

@AlexTeslenko Let me know if you have any further feedback to incorporate, makes sense for me to add some problems and if @AlexTeslenko has any feedback on the overall content or things to remove / change before merging PR.

The other consideration is surveying the other exercises for any complicated python syntax that isn't as explicit  and hasn't been covered in the python principle exercises. I'll have a look at them today too.

**Comment by chris-lovejoy** [comment]
merging exercises into main, so that people working on other exercises have clearer visibility on it (received a query about it)

**Pull request merged**
